/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const clientIndexLazyImport = createFileRoute('/(client)/')()
const serverProfileLazyImport = createFileRoute('/(server)/profile')()
const serverDashboardLazyImport = createFileRoute('/(server)/dashboard')()
const clientInformationallLazyImport = createFileRoute(
  '/(client)/informationall',
)()
const authLoginLazyImport = createFileRoute('/(auth)/login')()
const clientBukuIndexLazyImport = createFileRoute('/(client)/buku/')()
const clientArtikelIndexLazyImport = createFileRoute('/(client)/artikel/')()
const serverdataYoutubeDataYoutubeIndexLazyImport = createFileRoute(
  '/(server)/(data-youtube)/data-youtube/',
)()
const serverdataPengurusDataPengurusIndexLazyImport = createFileRoute(
  '/(server)/(data-pengurus)/data-pengurus/',
)()
const serverdataHimpunanDataHimpunanIndexLazyImport = createFileRoute(
  '/(server)/(data-himpunan)/data-himpunan/',
)()
const serverdataBukuDataBukuIndexLazyImport = createFileRoute(
  '/(server)/(data-buku)/data-buku/',
)()
const serverdataBarangDataBarangIndexLazyImport = createFileRoute(
  '/(server)/(data-barang)/data-barang/',
)()
const serverdataArtikelDataArtikelIndexLazyImport = createFileRoute(
  '/(server)/(data-artikel)/data-artikel/',
)()
const serverdataAlumniDataAlumniIndexLazyImport = createFileRoute(
  '/(server)/(data-alumni)/data-alumni/',
)()
const serverdataAdminDataAdminIndexLazyImport = createFileRoute(
  '/(server)/(data-admin)/data-admin/',
)()
const serverdataYoutubeDataYoutubeCreateLazyImport = createFileRoute(
  '/(server)/(data-youtube)/data-youtube/create',
)()
const serverdataPengurusDataPengurusCreateLazyImport = createFileRoute(
  '/(server)/(data-pengurus)/data-pengurus/create',
)()
const serverdataBukuDataBukuCreateLazyImport = createFileRoute(
  '/(server)/(data-buku)/data-buku/create',
)()
const serverdataBarangDataBarangCreateLazyImport = createFileRoute(
  '/(server)/(data-barang)/data-barang/create',
)()
const serverdataArtikelDataArtikelCreateLazyImport = createFileRoute(
  '/(server)/(data-artikel)/data-artikel/create',
)()
const serverdataAlumniDataAlumniCreateLazyImport = createFileRoute(
  '/(server)/(data-alumni)/data-alumni/create',
)()
const serverdataAdminDataAdminCreateLazyImport = createFileRoute(
  '/(server)/(data-admin)/data-admin/create',
)()
const clientBukuIdBukuLazyImport = createFileRoute('/(client)/buku/$id/buku')()
const clientArtikelIdInstagramLazyImport = createFileRoute(
  '/(client)/artikel/$id/instagram',
)()
const clientArtikelIdArtikelLazyImport = createFileRoute(
  '/(client)/artikel/$id/artikel',
)()
const serverdataYoutubeDataYoutubeIdEditLazyImport = createFileRoute(
  '/(server)/(data-youtube)/data-youtube/$id/edit',
)()
const serverdataPengurusDataPengurusIdEditLazyImport = createFileRoute(
  '/(server)/(data-pengurus)/data-pengurus/$id/edit',
)()
const serverdataBukuDataBukuIdEditLazyImport = createFileRoute(
  '/(server)/(data-buku)/data-buku/$id/edit',
)()
const serverdataBarangDataBarangIdEditLazyImport = createFileRoute(
  '/(server)/(data-barang)/data-barang/$id/edit',
)()
const serverdataArtikelDataArtikelIdEditLazyImport = createFileRoute(
  '/(server)/(data-artikel)/data-artikel/$id/edit',
)()
const serverdataAlumniDataAlumniIdEditLazyImport = createFileRoute(
  '/(server)/(data-alumni)/data-alumni/$id/edit',
)()
const serverdataAdminDataAdminIdEditLazyImport = createFileRoute(
  '/(server)/(data-admin)/data-admin/$id/edit',
)()

// Create/Update Routes

const clientIndexLazyRoute = clientIndexLazyImport
  .update({
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(client)/index.lazy').then((d) => d.Route))

const serverProfileLazyRoute = serverProfileLazyImport
  .update({
    path: '/profile',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(server)/profile.lazy').then((d) => d.Route))

const serverDashboardLazyRoute = serverDashboardLazyImport
  .update({
    path: '/dashboard',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(server)/dashboard.lazy').then((d) => d.Route))

const clientInformationallLazyRoute = clientInformationallLazyImport
  .update({
    path: '/informationall',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(client)/informationall.lazy').then((d) => d.Route),
  )

const authLoginLazyRoute = authLoginLazyImport
  .update({
    path: '/login',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))

const clientBukuIndexLazyRoute = clientBukuIndexLazyImport
  .update({
    path: '/buku/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(client)/buku.index.lazy').then((d) => d.Route))

const clientArtikelIndexLazyRoute = clientArtikelIndexLazyImport
  .update({
    path: '/artikel/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(client)/artikel.index.lazy').then((d) => d.Route),
  )

const serverdataYoutubeDataYoutubeIndexLazyRoute =
  serverdataYoutubeDataYoutubeIndexLazyImport
    .update({
      path: '/data-youtube/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-youtube)/data-youtube.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataPengurusDataPengurusIndexLazyRoute =
  serverdataPengurusDataPengurusIndexLazyImport
    .update({
      path: '/data-pengurus/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-pengurus)/data-pengurus.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataHimpunanDataHimpunanIndexLazyRoute =
  serverdataHimpunanDataHimpunanIndexLazyImport
    .update({
      path: '/data-himpunan/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-himpunan)/data-himpunan.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataBukuDataBukuIndexLazyRoute =
  serverdataBukuDataBukuIndexLazyImport
    .update({
      path: '/data-buku/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-buku)/data-buku.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataBarangDataBarangIndexLazyRoute =
  serverdataBarangDataBarangIndexLazyImport
    .update({
      path: '/data-barang/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-barang)/data-barang.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataArtikelDataArtikelIndexLazyRoute =
  serverdataArtikelDataArtikelIndexLazyImport
    .update({
      path: '/data-artikel/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-artikel)/data-artikel.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataAlumniDataAlumniIndexLazyRoute =
  serverdataAlumniDataAlumniIndexLazyImport
    .update({
      path: '/data-alumni/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-alumni)/data-alumni.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataAdminDataAdminIndexLazyRoute =
  serverdataAdminDataAdminIndexLazyImport
    .update({
      path: '/data-admin/',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-admin)/data-admin.index.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataYoutubeDataYoutubeCreateLazyRoute =
  serverdataYoutubeDataYoutubeCreateLazyImport
    .update({
      path: '/data-youtube/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-youtube)/data-youtube.create.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataPengurusDataPengurusCreateLazyRoute =
  serverdataPengurusDataPengurusCreateLazyImport
    .update({
      path: '/data-pengurus/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(server)/(data-pengurus)/data-pengurus.create.lazy'
      ).then((d) => d.Route),
    )

const serverdataBukuDataBukuCreateLazyRoute =
  serverdataBukuDataBukuCreateLazyImport
    .update({
      path: '/data-buku/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-buku)/data-buku.create.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataBarangDataBarangCreateLazyRoute =
  serverdataBarangDataBarangCreateLazyImport
    .update({
      path: '/data-barang/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-barang)/data-barang.create.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataArtikelDataArtikelCreateLazyRoute =
  serverdataArtikelDataArtikelCreateLazyImport
    .update({
      path: '/data-artikel/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-artikel)/data-artikel.create.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataAlumniDataAlumniCreateLazyRoute =
  serverdataAlumniDataAlumniCreateLazyImport
    .update({
      path: '/data-alumni/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-alumni)/data-alumni.create.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataAdminDataAdminCreateLazyRoute =
  serverdataAdminDataAdminCreateLazyImport
    .update({
      path: '/data-admin/create',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-admin)/data-admin.create.lazy').then(
        (d) => d.Route,
      ),
    )

const clientBukuIdBukuLazyRoute = clientBukuIdBukuLazyImport
  .update({
    path: '/buku/$id/buku',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(client)/buku_.$id.buku.lazy').then((d) => d.Route),
  )

const clientArtikelIdInstagramLazyRoute = clientArtikelIdInstagramLazyImport
  .update({
    path: '/artikel/$id/instagram',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(client)/artikel_.$id.instagram.lazy').then(
      (d) => d.Route,
    ),
  )

const clientArtikelIdArtikelLazyRoute = clientArtikelIdArtikelLazyImport
  .update({
    path: '/artikel/$id/artikel',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(client)/artikel_.$id.artikel.lazy').then((d) => d.Route),
  )

const serverdataYoutubeDataYoutubeIdEditLazyRoute =
  serverdataYoutubeDataYoutubeIdEditLazyImport
    .update({
      path: '/data-youtube/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(server)/(data-youtube)/data-youtube_.$id.edit.lazy'
      ).then((d) => d.Route),
    )

const serverdataPengurusDataPengurusIdEditLazyRoute =
  serverdataPengurusDataPengurusIdEditLazyImport
    .update({
      path: '/data-pengurus/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(server)/(data-pengurus)/data-pengurus_.$id.edit.lazy'
      ).then((d) => d.Route),
    )

const serverdataBukuDataBukuIdEditLazyRoute =
  serverdataBukuDataBukuIdEditLazyImport
    .update({
      path: '/data-buku/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-buku)/data-buku_.$id.edit.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataBarangDataBarangIdEditLazyRoute =
  serverdataBarangDataBarangIdEditLazyImport
    .update({
      path: '/data-barang/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-barang)/data-barang_.$id.edit.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataArtikelDataArtikelIdEditLazyRoute =
  serverdataArtikelDataArtikelIdEditLazyImport
    .update({
      path: '/data-artikel/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(server)/(data-artikel)/data-artikel_.$id.edit.lazy'
      ).then((d) => d.Route),
    )

const serverdataAlumniDataAlumniIdEditLazyRoute =
  serverdataAlumniDataAlumniIdEditLazyImport
    .update({
      path: '/data-alumni/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-alumni)/data-alumni_.$id.edit.lazy').then(
        (d) => d.Route,
      ),
    )

const serverdataAdminDataAdminIdEditLazyRoute =
  serverdataAdminDataAdminIdEditLazyImport
    .update({
      path: '/data-admin/$id/edit',
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import('./routes/(server)/(data-admin)/data-admin_.$id.edit.lazy').then(
        (d) => d.Route,
      ),
    )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/informationall': {
      id: '/informationall'
      path: '/informationall'
      fullPath: '/informationall'
      preLoaderRoute: typeof clientInformationallLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof serverDashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof serverProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof clientIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof clientArtikelIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/buku/': {
      id: '/buku/'
      path: '/buku'
      fullPath: '/buku'
      preLoaderRoute: typeof clientBukuIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/artikel/$id/artikel': {
      id: '/artikel/$id/artikel'
      path: '/artikel/$id/artikel'
      fullPath: '/artikel/$id/artikel'
      preLoaderRoute: typeof clientArtikelIdArtikelLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/artikel/$id/instagram': {
      id: '/artikel/$id/instagram'
      path: '/artikel/$id/instagram'
      fullPath: '/artikel/$id/instagram'
      preLoaderRoute: typeof clientArtikelIdInstagramLazyImport
      parentRoute: typeof rootRoute
    }
    '/(client)/buku/$id/buku': {
      id: '/buku/$id/buku'
      path: '/buku/$id/buku'
      fullPath: '/buku/$id/buku'
      preLoaderRoute: typeof clientBukuIdBukuLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-admin)/data-admin/create': {
      id: '/data-admin/create'
      path: '/data-admin/create'
      fullPath: '/data-admin/create'
      preLoaderRoute: typeof serverdataAdminDataAdminCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-alumni)/data-alumni/create': {
      id: '/data-alumni/create'
      path: '/data-alumni/create'
      fullPath: '/data-alumni/create'
      preLoaderRoute: typeof serverdataAlumniDataAlumniCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-artikel)/data-artikel/create': {
      id: '/data-artikel/create'
      path: '/data-artikel/create'
      fullPath: '/data-artikel/create'
      preLoaderRoute: typeof serverdataArtikelDataArtikelCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-barang)/data-barang/create': {
      id: '/data-barang/create'
      path: '/data-barang/create'
      fullPath: '/data-barang/create'
      preLoaderRoute: typeof serverdataBarangDataBarangCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-buku)/data-buku/create': {
      id: '/data-buku/create'
      path: '/data-buku/create'
      fullPath: '/data-buku/create'
      preLoaderRoute: typeof serverdataBukuDataBukuCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-pengurus)/data-pengurus/create': {
      id: '/data-pengurus/create'
      path: '/data-pengurus/create'
      fullPath: '/data-pengurus/create'
      preLoaderRoute: typeof serverdataPengurusDataPengurusCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-youtube)/data-youtube/create': {
      id: '/data-youtube/create'
      path: '/data-youtube/create'
      fullPath: '/data-youtube/create'
      preLoaderRoute: typeof serverdataYoutubeDataYoutubeCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-admin)/data-admin/': {
      id: '/data-admin/'
      path: '/data-admin'
      fullPath: '/data-admin'
      preLoaderRoute: typeof serverdataAdminDataAdminIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-alumni)/data-alumni/': {
      id: '/data-alumni/'
      path: '/data-alumni'
      fullPath: '/data-alumni'
      preLoaderRoute: typeof serverdataAlumniDataAlumniIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-artikel)/data-artikel/': {
      id: '/data-artikel/'
      path: '/data-artikel'
      fullPath: '/data-artikel'
      preLoaderRoute: typeof serverdataArtikelDataArtikelIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-barang)/data-barang/': {
      id: '/data-barang/'
      path: '/data-barang'
      fullPath: '/data-barang'
      preLoaderRoute: typeof serverdataBarangDataBarangIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-buku)/data-buku/': {
      id: '/data-buku/'
      path: '/data-buku'
      fullPath: '/data-buku'
      preLoaderRoute: typeof serverdataBukuDataBukuIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-himpunan)/data-himpunan/': {
      id: '/data-himpunan/'
      path: '/data-himpunan'
      fullPath: '/data-himpunan'
      preLoaderRoute: typeof serverdataHimpunanDataHimpunanIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-pengurus)/data-pengurus/': {
      id: '/data-pengurus/'
      path: '/data-pengurus'
      fullPath: '/data-pengurus'
      preLoaderRoute: typeof serverdataPengurusDataPengurusIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-youtube)/data-youtube/': {
      id: '/data-youtube/'
      path: '/data-youtube'
      fullPath: '/data-youtube'
      preLoaderRoute: typeof serverdataYoutubeDataYoutubeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-admin)/data-admin/$id/edit': {
      id: '/data-admin/$id/edit'
      path: '/data-admin/$id/edit'
      fullPath: '/data-admin/$id/edit'
      preLoaderRoute: typeof serverdataAdminDataAdminIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-alumni)/data-alumni/$id/edit': {
      id: '/data-alumni/$id/edit'
      path: '/data-alumni/$id/edit'
      fullPath: '/data-alumni/$id/edit'
      preLoaderRoute: typeof serverdataAlumniDataAlumniIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-artikel)/data-artikel/$id/edit': {
      id: '/data-artikel/$id/edit'
      path: '/data-artikel/$id/edit'
      fullPath: '/data-artikel/$id/edit'
      preLoaderRoute: typeof serverdataArtikelDataArtikelIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-barang)/data-barang/$id/edit': {
      id: '/data-barang/$id/edit'
      path: '/data-barang/$id/edit'
      fullPath: '/data-barang/$id/edit'
      preLoaderRoute: typeof serverdataBarangDataBarangIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-buku)/data-buku/$id/edit': {
      id: '/data-buku/$id/edit'
      path: '/data-buku/$id/edit'
      fullPath: '/data-buku/$id/edit'
      preLoaderRoute: typeof serverdataBukuDataBukuIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-pengurus)/data-pengurus/$id/edit': {
      id: '/data-pengurus/$id/edit'
      path: '/data-pengurus/$id/edit'
      fullPath: '/data-pengurus/$id/edit'
      preLoaderRoute: typeof serverdataPengurusDataPengurusIdEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/(server)/(data-youtube)/data-youtube/$id/edit': {
      id: '/data-youtube/$id/edit'
      path: '/data-youtube/$id/edit'
      fullPath: '/data-youtube/$id/edit'
      preLoaderRoute: typeof serverdataYoutubeDataYoutubeIdEditLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  authLoginLazyRoute,
  clientInformationallLazyRoute,
  serverDashboardLazyRoute,
  serverProfileLazyRoute,
  clientIndexLazyRoute,
  clientArtikelIndexLazyRoute,
  clientBukuIndexLazyRoute,
  clientArtikelIdArtikelLazyRoute,
  clientArtikelIdInstagramLazyRoute,
  clientBukuIdBukuLazyRoute,
  serverdataAdminDataAdminCreateLazyRoute,
  serverdataAlumniDataAlumniCreateLazyRoute,
  serverdataArtikelDataArtikelCreateLazyRoute,
  serverdataBarangDataBarangCreateLazyRoute,
  serverdataBukuDataBukuCreateLazyRoute,
  serverdataPengurusDataPengurusCreateLazyRoute,
  serverdataYoutubeDataYoutubeCreateLazyRoute,
  serverdataAdminDataAdminIndexLazyRoute,
  serverdataAlumniDataAlumniIndexLazyRoute,
  serverdataArtikelDataArtikelIndexLazyRoute,
  serverdataBarangDataBarangIndexLazyRoute,
  serverdataBukuDataBukuIndexLazyRoute,
  serverdataHimpunanDataHimpunanIndexLazyRoute,
  serverdataPengurusDataPengurusIndexLazyRoute,
  serverdataYoutubeDataYoutubeIndexLazyRoute,
  serverdataAdminDataAdminIdEditLazyRoute,
  serverdataAlumniDataAlumniIdEditLazyRoute,
  serverdataArtikelDataArtikelIdEditLazyRoute,
  serverdataBarangDataBarangIdEditLazyRoute,
  serverdataBukuDataBukuIdEditLazyRoute,
  serverdataPengurusDataPengurusIdEditLazyRoute,
  serverdataYoutubeDataYoutubeIdEditLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/informationall",
        "/dashboard",
        "/profile",
        "/",
        "/artikel/",
        "/buku/",
        "/artikel/$id/artikel",
        "/artikel/$id/instagram",
        "/buku/$id/buku",
        "/data-admin/create",
        "/data-alumni/create",
        "/data-artikel/create",
        "/data-barang/create",
        "/data-buku/create",
        "/data-pengurus/create",
        "/data-youtube/create",
        "/data-admin/",
        "/data-alumni/",
        "/data-artikel/",
        "/data-barang/",
        "/data-buku/",
        "/data-himpunan/",
        "/data-pengurus/",
        "/data-youtube/",
        "/data-admin/$id/edit",
        "/data-alumni/$id/edit",
        "/data-artikel/$id/edit",
        "/data-barang/$id/edit",
        "/data-buku/$id/edit",
        "/data-pengurus/$id/edit",
        "/data-youtube/$id/edit"
      ]
    },
    "/login": {
      "filePath": "(auth)/login.lazy.tsx"
    },
    "/informationall": {
      "filePath": "(client)/informationall.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "(server)/dashboard.lazy.tsx"
    },
    "/profile": {
      "filePath": "(server)/profile.lazy.tsx"
    },
    "/": {
      "filePath": "(client)/index.lazy.tsx"
    },
    "/artikel/": {
      "filePath": "(client)/artikel.index.lazy.tsx"
    },
    "/buku/": {
      "filePath": "(client)/buku.index.lazy.tsx"
    },
    "/artikel/$id/artikel": {
      "filePath": "(client)/artikel_.$id.artikel.lazy.tsx"
    },
    "/artikel/$id/instagram": {
      "filePath": "(client)/artikel_.$id.instagram.lazy.tsx"
    },
    "/buku/$id/buku": {
      "filePath": "(client)/buku_.$id.buku.lazy.tsx"
    },
    "/data-admin/create": {
      "filePath": "(server)/(data-admin)/data-admin.create.lazy.tsx"
    },
    "/data-alumni/create": {
      "filePath": "(server)/(data-alumni)/data-alumni.create.lazy.tsx"
    },
    "/data-artikel/create": {
      "filePath": "(server)/(data-artikel)/data-artikel.create.lazy.tsx"
    },
    "/data-barang/create": {
      "filePath": "(server)/(data-barang)/data-barang.create.lazy.tsx"
    },
    "/data-buku/create": {
      "filePath": "(server)/(data-buku)/data-buku.create.lazy.tsx"
    },
    "/data-pengurus/create": {
      "filePath": "(server)/(data-pengurus)/data-pengurus.create.lazy.tsx"
    },
    "/data-youtube/create": {
      "filePath": "(server)/(data-youtube)/data-youtube.create.lazy.tsx"
    },
    "/data-admin/": {
      "filePath": "(server)/(data-admin)/data-admin.index.lazy.tsx"
    },
    "/data-alumni/": {
      "filePath": "(server)/(data-alumni)/data-alumni.index.lazy.tsx"
    },
    "/data-artikel/": {
      "filePath": "(server)/(data-artikel)/data-artikel.index.lazy.tsx"
    },
    "/data-barang/": {
      "filePath": "(server)/(data-barang)/data-barang.index.lazy.tsx"
    },
    "/data-buku/": {
      "filePath": "(server)/(data-buku)/data-buku.index.lazy.tsx"
    },
    "/data-himpunan/": {
      "filePath": "(server)/(data-himpunan)/data-himpunan.index.lazy.tsx"
    },
    "/data-pengurus/": {
      "filePath": "(server)/(data-pengurus)/data-pengurus.index.lazy.tsx"
    },
    "/data-youtube/": {
      "filePath": "(server)/(data-youtube)/data-youtube.index.lazy.tsx"
    },
    "/data-admin/$id/edit": {
      "filePath": "(server)/(data-admin)/data-admin_.$id.edit.lazy.tsx"
    },
    "/data-alumni/$id/edit": {
      "filePath": "(server)/(data-alumni)/data-alumni_.$id.edit.lazy.tsx"
    },
    "/data-artikel/$id/edit": {
      "filePath": "(server)/(data-artikel)/data-artikel_.$id.edit.lazy.tsx"
    },
    "/data-barang/$id/edit": {
      "filePath": "(server)/(data-barang)/data-barang_.$id.edit.lazy.tsx"
    },
    "/data-buku/$id/edit": {
      "filePath": "(server)/(data-buku)/data-buku_.$id.edit.lazy.tsx"
    },
    "/data-pengurus/$id/edit": {
      "filePath": "(server)/(data-pengurus)/data-pengurus_.$id.edit.lazy.tsx"
    },
    "/data-youtube/$id/edit": {
      "filePath": "(server)/(data-youtube)/data-youtube_.$id.edit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
